using Application.Common.Interfaces;
using Infrastructure.Data;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Infrastructure;

public static class DependencyInjection
{
    public static IServiceCollection AddInfrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        var rawConnectionString = configuration.GetConnectionString("DefaultConnection")
            ?? throw new InvalidOperationException("Connection string 'DefaultConnection' not found.");

        var connectionString = NormalizeConnectionString(rawConnectionString);

        services.AddDbContext<AppDbContext>(options =>
            options.UseSqlServer(connectionString, sql =>
                sql.EnableRetryOnFailure(3)));

        services.AddScoped<IApplicationDbContext>(sp => sp.GetRequiredService<AppDbContext>());

        return services;
    }

    private static string NormalizeConnectionString(string rawConnectionString)
    {
        try
        {
            var builder = new SqlConnectionStringBuilder(rawConnectionString);

            if (builder.IntegratedSecurity)
            {
                builder.Remove("User ID");
                builder.Remove("Password");
            }

            builder.TrustServerCertificate = true;
            builder.MultipleActiveResultSets = true;

            return builder.ConnectionString;
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException(
                "Connection string 'DefaultConnection' is invalid. Review the database settings generated by the configurator.",
                ex);
        }
    }
}
